version: '3.5'

services:
  sistema.tjmt.jus.br:
    image: ${DOCKER_REGISTRY}sistema${ENVIRONMENT:--qa}.tjmt.jus.br:${VERSION:-latest}${LIFECYCLE_VERSION}
    labels:
      kompose.service.expose: sistema${ENVIRONMENT:--qa}.tjmt.jus.br
    hostname: sistema${ENVIRONMENT:--qa}.tjmt.jus.br
