version: '3.5'

services:
  sistema-tjmt-jus-br:
    build:
      target: release
    environment:
      DOCKER_REGISTRY: ${DOCKER_REGISTRY}
      VERSION: ${VERSION:-latest}
      BRANCH: ${BRANCH:-develop}
      ENVIRONMENT: ${ENVIRONMENT:-override}
    volumes:
      - ./kubeconfig:/bitnami/kubeconfig
