version: '3.5'

services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
#     networks:
#       - sonarqube

# networks:
#   sonarqube:
#     name: sonarqube
