version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:${BRANCH:-develop}.${VERSION:-latest}-publish
    container_name: sistema-${BRANCH:-develop}-publish.tjmt.jus.br
    build:
      target: release
    volumes:
      - app:/var/run/

volumes:
  app:
    name: ${DOCKERCOMPOSE_PUBLISH_VOLUME_NAME:-sistema-extract-app}