version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:local
    build:
      target: build
    ports:
      - 4200:4200      
    environment:
      RUN_TEST: ${RUN_TEST:-false}
      RUN_PROJECT: ${RUN_PROJECT:-true}
    depends_on:
      - sistema-api-tjmt-jus-br
    container_name: sistema-local.tjmt.jus.br

  sistema-api-tjmt-jus-br:
    image: suhailtaj/mock-api:${SISTEMA_API_VERSION:-latest}
    command: /usr/data/db.json
    volumes:
      - ./data/db.json:/usr/data/db.json
    ports:
      - 9090:9090
    container_name: sistema-api-local.tjmt.jus.br
