version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:${BRANCH:-develop}.${VERSION:-local}-build
    environment:
      RUN_TEST: ${RUN_TEST:-false}
      RUN_PROJECT: ${RUN_PROJECT:-true}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M         
    ports:
      - 80:4200
    labels:
      kompose.service.expose: sistema-${BRANCH:-develop}-dev.tjmt.jus.br

  sistema-api-tjmt-jus-br:
    image: suhailtaj/mock-api:${SISTEMA_API_VERSION:-latest}
    command: /usr/data/db.json
    volumes:
      - ./data/db.json:/usr/data/db.json
    ports:
      - 80:9090
    labels:
      kompose.service.expose: sistema-api-${BRANCH:-develop}-dev.tjmt.jus.br

networks:
  default:
    name: ns-sistema-${BRANCH:-develop}-dev
