version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:${BRANCH:-develop}.${VERSION:-latest}-publish
    build:
      target: publish
    volumes:
      - app:/app

volumes:
  app:
    name: ${DOCKERCOMPOSE_APP_VOLUME_NAME:-sistema-extract-app}
      