version: '3.5'

services:
  sistema.tjmt.jus.br:
    image: sistema.tjmt.jus.br:${STAGE-build}
    # build:
    #   context: .
    #   target: ${STAGE-ci}
    #   args:
    #     SONARQUBE: http://192.168.0.13:9000
    #     SONARQUBE_PROJECT: sistema.tjmt.jus.br
    #   cache_from:
    #     - sistema.tjmt.jus.br:build
    # ports:
    #   - 8080:8080
      #- 443:443
