version: '3.5'

services:
  sistema-tjmt-jus-br:
    build:
      target: release
    environment:
      BRANCH: ${BRANCH}
      ENVIRONMENT: ${ENVIRONMENT:-override}
    volumes:
      - ./kubeconfig:/bitnami/kubeconfig
