version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:${BRANCH:-develop}.${VERSION:-latest}-publish
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-override}
      NPM_LIFE_CICLE_VERSION: ${NPM_LIFE_CICLE_VERSION}
      DEPLOY_NPM: true
      DEPLOY_KUBERNETES: true
