version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:${BRANCH:-develop}.${VERSION:-latest}-build
    container_name: sistema-${BRANCH:-develop}-ci.tjmt.jus.br
    build:
      target: build
    environment:
      RUN_TEST: ${RUN_TEST:-true}
      RUN_PROJECT: ${RUN_PROJECT:-false}
    # depends_on:
    #   - sistema-api-tjmt-jus-br
    volumes:
      - test-result:/app/TestResults

  # sistema-api-tjmt-jus-br:
  #   image: suhailtaj/mock-api:${SISTEMA_API_VERSION:-latest}
  #   command: /usr/data/db.json
  #   volumes:
  #     -  ${PWD}/data/db.json:/usr/data/db.json
  #   ports:
  #     - 9090:9090
  #   container_name: sistema-api-${BRANCH:-develop}-ci.tjmt.jus.br

networks:
  default:
    name: ns-sistema-ci

volumes:
  test-result:
    name: ${DOCKERCOMPOSE_BUILD_VOLUME_NAME:-sistema-test-results}
