version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:${BRANCH:-develop}.${VERSION:-local}-publish
    container_name: sistema-${BRANCH:-develop}-publish.tjmt.jus.br
    build:
      target: release
      args:
        VERSION: ${VERSION:-local}
        BRANCH: ${BRANCH:-develop}
    volumes:
      - app:/var/release/

volumes:
  app:
    name: ${DOCKERCOMPOSE_PUBLISH_VOLUME_NAME:-sistema-extract-app}