version: '3.5'

services:
  sistema.tjmt.jus.br:
    image: sistema.tjmt.jus.br:${VERSION-latest}${LIFECYCLE_VERSION}-build
    build:
      context: .
      target: build
      args:
        SONARQUBE: http://192.168.0.13:9000
        SONARQUBE_PROJECT: sistema.tjmt.jus.br
    ports:
      - 8080:4200
    depends_on:
      - sistema-api.tjmt.jus.br

  sistema-api.tjmt.jus.br:
    image: suhailtaj/mock-api
    command: /usr/data/db.json
    volumes:
      - ./db.json:/usr/data/db.json
    ports:
      - 4000:9090
