version: '3.5'

services:
  sistema.tjmt.jus.br:
    image: ${DOCKER_REGISTRY}sistema-${BRANCH:?}.tjmt.jus.br:${VERSION:-latest}${LIFECYCLE_VERSION}
    labels:
      kompose.service.expose: sistema-${BRANCH:?}.tjmt.jus.br
    hostname: sistema-${BRANCH:?}-dev.tjmt.jus.br
