version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:${BRANCH:-develop}.${VERSION:-local}-publish
    environment:
      DOCKER_REGISTRY: ${DOCKER_REGISTRY}
      ENVIRONMENT: ${ENVIRONMENT}
      NPM_LIFE_CICLE_VERSION: ${NPM_LIFE_CICLE_VERSION}
      DEPLOY_NPM: ${DEPLOY_NPM:-true}
      DEPLOY_KUBERNETES: ${DEPLOY_KUBERNETES:-true}
      DESTROY_KUBERNETES_ENVIRONMENT: ${DESTROY_KUBERNETES_ENVIRONMENT:-false}

networks:
  default:
    name: ns-sistema-${BRANCH:-develop}-${ENVIRONMENT}-${VERSION}-release