version: '3.5'

services:
  sistema-tjmt-jus-br:
    image: ${DOCKER_REGISTRY}sistema.tjmt.jus.br:${BRANCH}.${VERSION}
    ports:
      - 80:80
      - 443:443
    labels:
      kompose.service.expose: sistema.tjmt.jus.br

networks:
  default:
    name: ns-sistema
