version: '3.5'

services:
  sistema.tjmt.jus.br:
    image: ${DOCKER_REGISTRY}sistema-stage.tjmt.jus.br:${VERSION:-latest}
    labels:
      kompose.service.expose: sistema.tjmt.jus.br
    hostname: sistema.tjmt.jus.br
    environment:
      - variable: something
